version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: phani997/web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
  mongodb:
    image: phani997/mongodb:v1
    container_name: mongodb
  catalogue:
    image: phani997/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis