version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: phani997/web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
    - payment
    - ratings
  mongodb:
    image: phani997/mongodb:v1
    container_name: mongodb
  catalogue:
    image: phani997/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
  user:
    image: phani997/user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: phani997/cart:v2
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: phani997/mysql:v1
    container_name: mysql
  shipping:
    image: phani997/shipping:v2
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: phani997/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  ratings:
    image: phani997/ratings:v1
    container_name: ratings
    depends_on:
    - mysql